-- Languages --
INSERT INTO Language (langCode, title)
VALUES ('fa', 'فارسی')
     , ('en', 'English')
     , ('de', 'Duetch')
     , ('fr', 'French')
     , ('ar', 'العربیه')
     , ('cn', 'Chinese')
     , ('tr', 'Turkish')
     , ('admin', 'Japanese')
     , ('jp', 'Japanese')
;

-- Skills --
INSERT INTO Skill (skillId, title)
VALUES (1, 'SQL')
     , (2, 'Java')
     , (3, 'C++')
     , (4, 'Kotlin')
     , (5, 'Flutter')
     , (6, 'JS')
     , (7, 'React')
     , (8, 'CSS')
     , (9, 'HTML')
     , (10, 'Web')
     , (11, 'AppDevelopment')
     , (12, 'SoftwareDevelopment')
     , (13, 'WebDevelopment')
     , (14, 'Bootstrap')
     , (15, 'AI')
     , (16, 'Photoshop')
     , (17, 'Rust')
     , (18, 'Blender')
     , (19, 'Basic')
;

-- Users --
INSERT INTO User (userId, username, password, firstname, lastname, intro, about, avatar, accomp, birthday, location)
VALUES (1, 'admin', 'admin', 'Admin', 'Adminian', null, null, null, null, null, 'Iran')
     , (2, 'hossain', 'hossain', 'Hossain', 'Khademian', null, null, null, null, null, 'Fars')
     , (3, 'mamad', 'mamad', 'Mohammad', 'JahanDide', null, null, null, null, null, 'Iran')
     , (4, 'user959', 'user', 'fUser #959', 'lUser #959', null, null, null, null, null, null)
     , (5, 'user855', 'user', 'fUser #855', 'lUser #855', null, null, null, null, null, null)
     , (6, 'gholi', 'gholi', 'Gholi', 'Gholizade', null, null, null, null, null, null)
     , (7, 'test', 'test', 'test', 'test', null, null, null, null, null, null)
     , (8, 'action', 'action', 'action', 'action', null, null, null, null, null, null)
     , (9, 'ali', 'ali', 'Ali', 'Alinezhad', null, null, null, null, null, null)
     , (10, 'ramin', 'ramin', 'Ramin', 'Roshan', null, null, null, null, null, 'Shiraz')
     , (11, 'poria', 'poria', 'Pooria', 'behroozi', null, null, null, null, null, null)
     , (12, 'mina', 'mina', 'Mina', 'Minaian', null, null, null, null, null, null)
     , (13, 'nilo', 'nilo', 'Niloo', 'NilooPoor', null, null, null, null, null, 'London')
     , (14, 'anna', 'anna', 'Anna', 'Green', null, null, null, null, null, 'Berlin')
     , (15, 'mehdi', 'mehdi', 'Mehdi', 'Alizade', null, null, null, null, null, 'Qom')
;
